# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-s_V6lS3kUslSPAD2HcdTzouxvKhzKY
"""

def add(first_number, second_number):
    return first_number + second_number

def subtract(first_number, second_number):
    return first_number - second_number

def multiply(first_number, second_number):
    return first_number * second_number

def divide(first_number, second_number):
    if second_number != 0:
        return first_number / second_number
    else:
        return "Error: Division by zero is not allowed."

def calculator():
    operations = {
        '1': add,
        '2': subtract,
        '3': multiply,
        '4': divide
    }

    while True:
        print("\n=== Simple Calculator ===")
        print("Choose an operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '5':
            print("Exiting the calculator. Goodbye!")
            break

        try:
            first_number = float(input("Enter the first number: "))
            second_number = float(input("Enter the second number: "))

            if choice in operations:
                result = operations[choice](first_number, second_number)
                print(f"The result is: {result}")
            else:
                print("Invalid choice. Please select a valid option.")
        except ValueError:
            print("Invalid input. Please enter numeric values.")

calculator()
2